version: '3'
services:
  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes:
      - ./frontend:/app
    env_file:
      - ./.env.prod
    networks:
      - frontend

  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nextjs
    networks:
      - frontend

networks:
  frontend: