version: '3'
services:
  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    env_file:
      - ./.env.dev
    networks:
      - frontend
      - external-network

  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nextjs
    networks:
      - frontend

networks:
  frontend:
  external-network:
    external: true